# Generated by Django 4.2.3 on 2023-08-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('intro', models.CharField(max_length=250, verbose_name='Вступление')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('datentime', models.DateTimeField(verbose_name='Дата и время публикации')),
            ],
        ),
    ]
